### ISSUE TITLE
VASP MLFF compatibility

### ISSUE THREAD

**Issue by Alexyjones** [ulissigroup/vasp-interactive#39]
Would it be possible to let vaspInteractive pass through the keywords needed for MLFF. I think it they just need to be passed on to the INCAR. 

In my case those are

 ml_lmlff = True
 ml_istart = 2
 ml_mconf = 2500
Learning the force field will likely not be possible, but using should be ok I guess. 

Thank you for a great tool!

Alex

**Comment by alchem0x2A** [comment]
Hi @Alexyjones thanks for the feedback! Yes I briefly checked with VASP 6.3 version and it should be possible. In this case VaspInteractive is still working as a stream calculator but the VASP backend decides whether to do the DFT with KS solver or MLFF. 

Please note the input parameters of VaspInteractive is just inherited from parent ase.calculators.vasp.Vasp, so mlff keywords are not recognized. You can simply use the `custom` keywords to send these:

```python
calc = VaspInteractive(custom={"ml_mlff": True, "ml_istart": 2, "ml_mconf": 2500}, **param)
```
https://gitlab.com/ase/ase/-/blob/master/ase/calculators/vasp/create_input.py#L1023 

I'm not satisfied with the MLFF in VASP as sometime it gets weird issues when used for optimization. But if you have a better example showing we can combine external optimizer with MLFF that'd be great. We can think of adding this to the example gallery

**Comment by Alexyjones** [comment]
Hi @alchem0x2A, thank you so much for your helpful answer. I tried the custom route and that works as intended. I noticed that the VASP ML energies seem to be not recognised by the calculator, hence it did not work as intended. My "feeling" is that the inclusion of ML in the energy statement messes with the pattern matching.

Example:

"ML energy  without entropy=      -19.19635413  ML energy(sigma->0) =      -19.19635413"

I am currently learning the MLFF feature and created a force field, but was thinking to do the extensive testing via the ASE interface. I am happy to provide an example, once it works properly. I actually would also like to test other machine learned potentials that might be helpful for optimising adsorbates at surfaces.

**Comment by alchem0x2A** [comment]
yeah you're right, with the new MLFF in vasp it's breaking the OUTCAR for ase parser and vasprun.xml is also only recording the DFT energies not the ML ones, so the calculator won't work as expected. I guess it's a bit complicated in this situation since ase reader will return different results on the trajectory even if the upstream source code is fixed. However I do want to have this feature added as people may want to use the MLFF for more than just doing MD. One possibility is to preprocess the OUTCAR lines when sent to `read_energy` `read_forces` etc whenever MLFF is activated, but that needs to be tested.

**Comment by alchem0x2A** [comment]
@Alexyjones I took a brief look at the MLFF outputs and there's a quick fix in PR #44. With example ex17 I tested several ways to combine MLFF + VaspInteractive + BFGS and seems there are no major issues. You can pull the lastest version and have a try.

**Comment by Alexyjones** [comment]
Thank you so much, no it works!

Best wishes

**Comment by alchem0x2A** [comment]
great. I'll close the issue for now. If you have a better example showing the usage of MLFF you're welcome to submit a PR :)
