### ISSUE TITLE
Question about ISYM

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [ulissigroup/vasp-interactive#49]
_Very_ cool project! I'm definitely going to try this out sometime.

In the README, it says
> Symmetry is disabled (isym=0) to avoid spurious error due to wavefunction symmetry mismatch between the steps.

Is that always forced to be the case or just the default? It'd be nice if I could set ISYM != 0, e.g., for a static calculation. Mostly just curious.

**Comment by alchem0x2A** [comment]
hi @arosen93 good question indeed. ISYM=0 is required for systems that switch from higher to lower symmetry during the calculation (for instance some cases in NEB), but for others (e.g. a normal relaxation) it may be quite safe to use default symmetry tags. The setting can be overwritten but the user should do some tests to double-check. The reasoning behind this can be found in https://github.com/ulissigroup/vasp-interactive/issues/17

**Comment by Andrew-S-Rosen** [comment]
Thanks! That makes sense. Sometimes ISYM=0 is valuable for static bandstructure calculations, so it's nice that it can be set off by the user (although I also like setting it off by default!). Looking forward to seeing if/when `vasp-interactive` is compatible with VASP 6.4.1+!
